//
//  Constants.h
//  eCommerceApp
//
//  Created by Rishabh Jain on 30/09/15.
//  Copyright (c) 2015 Twist Mobile. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface Constants : NSObject

//VIEW CONTROLLER STORYBOARD ID
FOUNDATION_EXPORT NSString *const STORYBOARD_NAME;
FOUNDATION_EXPORT NSString *const VC_SWREVEAL;
FOUNDATION_EXPORT NSString *const VC_MAIN;
FOUNDATION_EXPORT NSString *const VC_BOTTOM_BAR;
FOUNDATION_EXPORT NSString *const VC_TOP_BAR;
FOUNDATION_EXPORT NSString *const VC_BACK_BTN;
FOUNDATION_EXPORT NSString *const VC_BACK_BTN_CATEGORY;
FOUNDATION_EXPORT NSString *const VC_BACK_BTN_CATEGORY_NEW;
FOUNDATION_EXPORT NSString *const VC_BACK_BTN_ADDRESS;
FOUNDATION_EXPORT NSString *const VC_BACK_BTN_CART_CONFIRM;
FOUNDATION_EXPORT NSString *const VC_BACK_BTN_CART_SHIPPING;
FOUNDATION_EXPORT NSString *const VC_BACK_BTN_ORDER;
FOUNDATION_EXPORT NSString *const VC_BACK_BTN_ORDER_RECEIPT;
FOUNDATION_EXPORT NSString *const VC_WEBVIEW;
FOUNDATION_EXPORT NSString *const VC_BARCODE_SCAN;
FOUNDATION_EXPORT NSString *const VC_LOCATE_STORE;
FOUNDATION_EXPORT NSString *const VC_SELLER_ZONE;
FOUNDATION_EXPORT NSString *const VC_ADDRESS_MAP;
FOUNDATION_EXPORT NSString *const VC_CONTACT_US;
FOUNDATION_EXPORT NSString *const VC_CONTACT_US_FORM;
FOUNDATION_EXPORT NSString *const VC_RESERVATION_FORM;
FOUNDATION_EXPORT NSString *const VC_CHECKOUT;
FOUNDATION_EXPORT NSString *const VC_GETCODE;
FOUNDATION_EXPORT NSString *const VC_BACK_BTN_SPONSOR_FRIEND;
FOUNDATION_EXPORT NSString *const VC_FILTER;
FOUNDATION_EXPORT NSString *const VC_MYCOUPON;
FOUNDATION_EXPORT NSString *const VC_MYCOUPON_PRODUCT;
FOUNDATION_EXPORT NSString *const VC_NOTIFICATION;
FOUNDATION_EXPORT NSString *const VC_SETTING;
FOUNDATION_EXPORT NSString *const VC_SELLER_ITEM;
FOUNDATION_EXPORT NSString *const VC_PRODUCTS;
FOUNDATION_EXPORT NSString *const VC_NEARBYSEARCH;
FOUNDATION_EXPORT NSString *const VC_CURRENCY;
FOUNDATION_EXPORT NSString *const VC_BACK_BTN_LOGIN;
FOUNDATION_EXPORT NSString *const VC_BACK_BTN_PRODUCT;
FOUNDATION_EXPORT NSString *const VC_PROD_DESC;
FOUNDATION_EXPORT NSString *const VC_SPLASH_PRIMARY;
FOUNDATION_EXPORT NSString *const VC_SPLASH_PLATFORM;
FOUNDATION_EXPORT NSString *const VC_LEFT;
FOUNDATION_EXPORT NSString *const VC_RIGHT;
FOUNDATION_EXPORT NSString *const VC_SPLASH_SECONDARY;
FOUNDATION_EXPORT NSString *const VC_SPLASH_VENDOR;
FOUNDATION_EXPORT NSString *const VC_HOME;
FOUNDATION_EXPORT NSString *const VC_HOME_DYNAMIC;
FOUNDATION_EXPORT NSString *const VC_SEARCH;
FOUNDATION_EXPORT NSString *const VC_OPINION;
FOUNDATION_EXPORT NSString *const VC_CART;
FOUNDATION_EXPORT NSString *const VC_MY_ACCOUNT;
FOUNDATION_EXPORT NSString *const VC_WISHLIST;
FOUNDATION_EXPORT NSString *const VC_WITH_TAB_BAR;
FOUNDATION_EXPORT NSString *const VC_CENTER_TOP;
//SEGUE ID STORYBOARD
FOUNDATION_EXPORT NSString *const SEAGUE_VC_TOP_BAR;
FOUNDATION_EXPORT NSString *const SEAGUE_VC_BOTTOM_BAR;
FOUNDATION_EXPORT NSString *const SEAGUE_VC_CENTER_TOP;
//SEGUE ID CREATED RUNTIME
FOUNDATION_EXPORT NSString *const SEAGUE_VC_HOME;
FOUNDATION_EXPORT NSString *const SEAGUE_VC_HOME_DYNAMIC;
FOUNDATION_EXPORT NSString *const SEAGUE_VC_SEARCH;
FOUNDATION_EXPORT NSString *const SEAGUE_VC_OPINION;
FOUNDATION_EXPORT NSString *const SEAGUE_VC_CART;
FOUNDATION_EXPORT NSString *const SEAGUE_VC_MY_ACCOUNT;
FOUNDATION_EXPORT NSString *const SEAGUE_VC_WISHLIST;
FOUNDATION_EXPORT NSString *const SEAGUE_VC_BACK_BTN;


#define BANNER_ARRAY [NSArray arrayWithObjects:\
@"Banners/bnr1.jpg",\
@"Banners/bnr2.jpg",\
@"Banners/bnr4.jpg",\
@"Banners/bnr5.jpg",\
@"Banners/bnr3.jpg", nil]

//[NSArray arrayWithObjects: @"Banners/b7.png", @"Banners/b6.png", @"Banners/banner01.png", @"Banners/banner02.png", @"Banners/banner03.png", @"Banners/banner04.png", @"Banners/banner05.png", nil]
//FOUNDATION_EXPORT NSString * const BANNER_ARRAY[];
@end
